version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: isbd_postgres
    restart: always
    environment:
      POSTGRES_USER: isbd
      POSTGRES_PASSWORD: isbd
      POSTGRES_DB: poc_isbd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: isbd_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@isbd.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:
